version: '3.9'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP__BOT__TOKEN: ${APP__BOT__TOKEN}
      APP__POSTGRES__USER: ${APP__POSTGRES__USER}
      APP__POSTGRES__PASSWORD: ${APP__POSTGRES__PASSWORD}
      APP__POSTGRES__DB: ${APP__POSTGRES__DB}
      APP__POSTGRES__HOST: ${APP__POSTGRES__HOST}
      APP__POSTGRES__PORT: ${POSTGRES_PORT}
    depends_on:
      - db
    restart: always

  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
